language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

before_script:
  - cp errbot/config-travisci.py config.py

install:
  - python setup.py develop
  - pip freeze

script: python run_tests.py

# notification for gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/788e94bb42a75aa2df4c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
